"""add_timeline_events_to_reports

Revision ID: 21bbcb3cb51d
Revises: c600b8782d4b
Create Date: 2026-07-01 13:57:34.649978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21bbcb3cb51d'
down_revision: Union[str, None] = 'c600b8782d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_reports', sa.Column('timeline_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_reports', 'timeline_events')
    # ### end Alembic commands ###
